apiVersion: v1
kind: Service
metadata:
  name: admintool-service
  labels:
    service: admintool-service
spec:
  ports:
    -
      name: http
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
      targetPort: 443
  selector:
    app: admintool
  type: LoadBalancer
