apiVersion: v1
kind: ReplicationController
metadata:
  name: admintool-rc
spec:
  replicas: 1
  selector:
    app: admintool
  template:
    metadata:
      labels:
        app: admintool
    spec:
      containers:
        -
          image: gcr.io/djnro-containers/admintool_apache:latest
          name: apache
          env:
           - name: ENVVARS_FILE
             value: /srv/secrets/envvars
           - name: DJNRO_HOST
             value: localhost
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: apache-certs
              mountPath: /usr/local/apache2/conf/external
            - name: admintool-secrets-volume
              mountPath: /srv/secrets
        -
          image: gcr.io/djnro-containers/admintool_djnro:latest
          name: djnro
          env:
           - name: ENVVARS_FILE
             value: /srv/secrets/envvars
           - name: DB_HOST
             value: localhost
          ports:
            - containerPort: 3031
          volumeMounts:
            - name: admintool-secrets-volume
              mountPath: /srv/secrets
        -
          image: gcr.io/djnro-containers/admintool_postgres:latest
          name: postgres
          env:
           - name: ENVVARS_FILE
             value: /srv/secrets/envvars
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /vsr/lib/postgresql/data
            - name: admintool-secrets-volume
              mountPath: /srv/secrets
      volumes:
      - name: admintool-secrets-volume
        secret:
          secretName: admintool-secrets
      - name: apache-certs
        emptyDir:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: djnro-dev-postgres-pv-claim
