# TODO
# - Mail server?

#Admin Tool
###########

#reverse proxy / ssl termination / static file handling
apache:
    restart: always
    build: ./apache/
    #log_driver: syslog
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /etc/ssl:/etc/ssl:ro
    volumes_from:
        #get access to the static files.
        - djnro
        #?- kibana
    #links to reverse proxy the admin tool and kibana
    links:
        - "djnro:djnro"
        - "kibana:kibana"

djnro:
    restart: always
    build: ./djnro/
    #log_driver: syslog
    expose:
        - "3031"
    volumes:
        - /code
    links:
        - "postgres:postgres"

postgres:
    restart: always
    build: ./postgres/
    #log_driver: syslog
    expose:
        - "5432"
    volumes:
        - /var/lib/docker-host-volumes/postgres-data:/var/lib/postgresql/data

#ELK Stack
##########

elasticsearch:
    restart: always
    build: ./elasticsearch/
    #log_driver: syslog
    volumes:
        - /var/lib/docker-host-volumes/elasticsearch-data:/usr/share/elasticsearch/data

logstash:
    restart: always
    build: ./logstash/
    #log_driver: syslog
    volumes:
        - /var/lib/docker-host-volumes/logstash-data:/usr/share/logstash/data
    links:
        - "kibana:kibana"

kibana:
    restart: always
    build: ./kibana/
    #log_driver: syslog
    ports:
        - "5601:5601"
    links:
        - "elasticsearch:elasticsearch"

