icingaweb:
    restart: always
    build: ./icingaweb/
    container_name: icingaweb
    ports:
        # temporarily use alt ports to avoid clash with admintool
        - "8080:80"
        - "8443:443"
    volumes:
        - /var/lib/docker-host-volumes/icingaweb-apache-logs:/var/log/apache2
        - /var/lib/docker-host-volumes/icingaweb-logs:/var/log/icingaweb2
    volumes_from:
        # we need to see the Command Transport file
        - icinga
    links:
        - "postgres-icinga:postgres-icinga"

icinga:
    restart: always
    build: ./icinga/
    container_name: icinga
    volumes:
        - /var/lib/docker-host-volumes/icinga-cmd:/var/run/icinga2
        - /var/lib/docker-host-volumes/icinga-lib:/var/lib/icinga2
        - /var/lib/docker-host-volumes/icinga-logs:/var/log/icinga2
    links:
        - "postgres-icinga:postgres-icinga"


postgres-icinga:
    restart: always
    container_name: postgres-icinga
    build: ./postgres/
    #log_driver: syslog
    env_file: localdev_postgres.env
    volumes:
        - /var/lib/docker-host-volumes/postgres-icinga-data:/var/lib/postgresql/data
