version: '3'
services:

  icingaweb:
    restart: always
    build: ./icingaweb/
    container_name: icingaweb
    environment:
        HTTPS_PORT: 443
        ICINGA_DB_HOST: postgres-icinga
        ICINGAWEB2_DB_HOST: postgres-icinga
    env_file:
        - localdev_icinga.env
        - global-env.env
    ports:
        # temporarily use alt ports to avoid clash with admintool
        - "80:80"
        - "443:443"
    volumes:
        - icingaweb-apache-certs:/etc/apache2/certs
        - icingaweb-apache-logs:/var/log/apache2
        - icingaweb-logs:/var/log/icingaweb2
        # we need to access to the Command Transport file
        - icinga-cmd:/var/run/icinga2
    links:
        - "postgres:postgres-icinga"

  icinga:
    restart: always
    build: ./icinga/
    container_name: icinga
    environment:
        ICINGA_DB_HOST: postgres-icinga
    env_file:
        - localdev_icinga.env
        - global-env.env
    volumes:
        - icinga-external-conf:/etc/icinga2/externalconf
        - icinga-cmd:/var/run/icinga2
        - icinga-lib:/var/lib/icinga2
        - icinga-logs:/var/log/icinga2
    links:
        - "postgres:postgres-icinga"


  postgres:
    restart: always
    container_name: postgres-icinga
    build: ./postgres/
    env_file:
        - localdev_icinga.env
        - global-env.env
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  #  all volume names will get prefixed with the project name - "icinga_"
  icingaweb-apache-certs: {}
  icingaweb-apache-logs: {}
  icingaweb-logs: {}
  icinga-external-conf: {}
  icinga-cmd: {}
  icinga-lib: {}
  icinga-logs: {}
  postgres-data: {}
