elasticsearch:
    restart: always
    build: ./elasticsearch/
    container_name: elasticsearch
    #log_driver: syslog
    volumes:
        - /var/lib/docker-host-volumes/elasticsearch-data:/usr/share/elasticsearch/data

logstash:
    restart: always
    build: ./logstash/
    container_name: logstash
    #log_driver: syslog
    volumes:
        - /var/lib/docker-host-volumes/logstash-data:/usr/share/logstash/data
    links:
        - "elasticsearch:elasticsearch"

kibana:
    restart: always
    build: ./kibana/
    container_name: kibana
    #log_driver: syslog
    ports:
        - "5601:5601"
    links:
        - "elasticsearch:elasticsearch"
