# TODO
# - Mail transport

#reverse proxy / ssl termination / static file handling
apache:
    restart: always
    build: ./apache/
    container_name: apache
    #log_driver: syslog
    environment:
        DJNRO_HOST: djnro
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/lib/docker-host-volumes/apache-certs:/usr/local/apache2/conf/external
    volumes_from:
        #get access to the static files.
        - djnro
        #?- kibana
    #links to reverse proxy the admin tool and kibana
    links:
        - "djnro:djnro"
        #- "kibana:kibana"

djnro:
    restart: always
    build: ./djnro/
    container_name: djnro
    #log_driver: syslog
    environment:
        DB_HOST: postgres
    env_file: localdev_djnro.env
    volumes:
        - /code
    links:
        - "postgres:postgres"

postgres:
    restart: always
    container_name: postgres
    build: ./postgres/
    #log_driver: syslog
    env_file: localdev_postgres.env
    volumes:
        - /var/lib/docker-host-volumes/postgres-data:/var/lib/postgresql/data
