version: '2'
services:

  elasticsearch:
    restart: always
    build: ./elasticsearch/
    container_name: elasticsearch
    #log_driver: syslog
    env_file:
        - global-env.env
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    restart: always
    build: ./logstash/
    container_name: logstash
    #log_driver: syslog
    env_file:
        - localdev_elk.env
        - global-env.env
    ports:
        - "5043:5043"
    links:
        - "elasticsearch:elasticsearch"

  kibana:
    restart: always
    build: ./kibana/
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    #log_driver: syslog
    env_file:
        - localdev_elk.env
        - global-env.env
    links:
        - "elasticsearch:elasticsearch"

  #reverse proxy / ssl termination / authentication
  apache:
    restart: always
    build: ./apache-elk/
    container_name: apache-elk
    #log_driver: syslog
    environment:
        KIBANA_URL: http://kibana:5601/
        HTTPS_PORT: 443
        HTTPD_ARGS: -DAPACHE_LOGS_STDOUT
    env_file:
        - localdev_elk.env
        - global-env.env
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - apache-certs:/usr/local/apache2/conf/external
        - apache-logs:/usr/local/apache2/logs
    #links to reverse proxy and control access to Kibana
    links:
        - "kibana:kibana"

volumes:
  # all volume names will get prefixed with the project name - "elk_"
  elasticsearch-data: {}
  apache-certs: {}
  apache-logs: {}
