kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: djnro-dev-postgres-pv-claim
  labels:
    app: admintool
    service: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
